Repository VRLabs/Simple-Shader-Inspectors, pull requests merged in 2021-03, with the labels that each got.

#8 Set a default Section Alias
  Editor/Controls/Sections/Section.cs
Labels: bugfix

#10 Update SimpleShaderInspectorsDefinition.asmdef
  Editor/SimpleShaderInspectorsDefinition.asmdef
Labels: bugfix

#11 Add Action for automatic release on tag creation
  .github/release-notes.configuration.json
  .github/workflows/create-release.yml
Labels: new feature

#12 Fix Section example to correctly use the alias as for v0.2 update
  Examples/Additive effects shader/Editor/SimpleSectionedShaderGUI.cs
Labels: bugfix

#13 Fix name of changelog
  .github/release-notes-configuration.json
Labels: bugfix, ignore

#15 Update Artifacts
  .github/workflows/build-docs.yml
Labels: bugfix, documentation
